[package]
name = "nnus"
version = "0.1.0"
authors = ["Half-Shot <will@half-shot.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.20.0"
time = "0.1.42"
nickel = "0.11.0"
hyper = "0.10.16"